---
title: "Model fitting"
output: html_notebook
---

## Load input data
```{r}
myPath <- #ADD YOUR PATH TO GITHUB DATA
suppressPackageStartupMessages(library("DESeq2"))
suppressPackageStartupMessages(library("ggplot2"))

PAR1_genes <- c("AKAP17A","ASMT","ASMTL","CD99","CRLF2","CSF2RA","DHRSX","GTPBP6","IL3RA","P2RY8","PLCXD1","PPP2R3B","SHOX","SLC25A6","ZBED1")
PAR2_genes <- c("VAMP7","WASH6P","IL9R","SPRY3")

# extract normalized count data
data.lcl <- read.delim(file=paste0(myPath,"Linear_regressions/LCLs/lcl_normCounts_expXgenes.txt"), check.names = FALSE, stringsAsFactors = FALSE)
data.fib <- read.delim(file=paste0(myPath,"Linear_regressions/Fibroblasts/fib_normCounts_expXgenes.txt"), check.names = FALSE, stringsAsFactors = FALSE)

data.lcl.y <- read.delim(file=paste0(myPath,"Linear_regressions/LCLs/lcl_normCounts_expYgenes.txt"), check.names = FALSE, stringsAsFactors = FALSE)
data.fib.y <- read.delim(file=paste0(myPath,"Linear_regressions/Fibroblasts/fib_normCounts_expYgenes.txt"), check.names = FALSE, stringsAsFactors = FALSE)

metadata <- read.delim(file=paste0(myPath,"Linear_regressions/metadata.txt"), stringsAsFactors = FALSE)
meta.lcl <- metadata[metadata$cell_type == "LCL" & metadata$karyotype %in% c("X","XX","XXX","XXXX","XXXXY","XXXY","XXY","XXYY","XY","XYY","XYYYY") & metadata$Technical_replicate == "N",]
meta.fib <- metadata[metadata$cell_type == "Fib" & metadata$karyotype %in% c("X","XX","XXX","XXXX","XXXXY","XXXY","XXY","XXYY","XY","XYY","XYYYY") & metadata$Technical_replicate == "N",]
  
#order data by metadata sample order
data.fib <- data.fib[,meta.fib$sample]
data.lcl <- data.lcl[meta.lcl$sample]

meta.lcl.y <- metadata[metadata$cell_type == "LCL" & metadata$karyotype %in% c("XXXXY","XXXY","XXY","XXYY","XY","XYY","XYYYY") & metadata$Technical_replicate == "N",]
meta.fib.y <- metadata[metadata$cell_type == "Fib" & metadata$karyotype %in% c("XXXXY","XXXY","XXY","XXYY","XY","XYY","XYYYY") & metadata$Technical_replicate == "N",]

data.fib.y <- data.fib.y[,meta.fib.y$sample]
data.lcl.y <- data.lcl.y[meta.lcl.y$sample]
# note: geneAnno and gene sets loaded through asr_funcs_lite.R

#bring in Balaton consensus XCI annotations
balaton_XCI_anno <- read.delim(file=paste0(myPath,"Annotations/Balaton_annotations.txt"), stringsAsFactors = FALSE)
```

#NPX gene Modeling function
```{r}
fit_NLS_model <- function(data, meta, genes, myMax = 100, start_a = 1, start_b = 0.5){
  # data <- data.fib
  # meta <- meta.fib
  # genes <- fib_xgenes_fix
  # myMax <- 100
  # start_a <- 1
  # start_b <- 0.5
# format data
  rownames(meta) <- meta$sample
	mod <- model.matrix(~x_count + y_count, meta[colnames(data), ])
	mod[, 2] <- mod[, 2] - 1
	df <- t(data[genes, ])
	# normalize data to appropriate mean value
	# normalize to mean of samples with one X
	b0s <- apply(df[rownames(mod[mod[, 2]==0, ]),], 2, mean)
	df <- t(t(df) / b0s)

	# fit
	coefs <- list()
	for (g in genes) {
	  # g <- genes[1]
		df.g <- data.frame(cts=df[, g], x_count=mod[, 2], y_count=mod[, 3],
						   chrom_count=mod[, 2]+mod[, 3])
		m.g <- nlsLM(cts ~ 1 + b * x_count ^ a, df.g, start=list(a=start_a, b=start_b), control = nls.lm.control(maxiter = myMax,))
		coefs[[g]] <- c(m.g$m$getPars(), converged=m.g$convInfo$isConv, numConv = m.g$convInfo$finIter)
	}
	coefs <- as.data.frame(t(data.frame(coefs)))
	return(coefs)
}
```

## LCL all NPX
```{r}
#LCL: all NPX genes
lcl_xgenes <- rownames(data.lcl)[! rownames(data.lcl) %in% c(PAR1_genes, PAR2_genes)] 
lcl_xgenes_fix <- lcl_xgenes[! lcl_xgenes %in% c("XIST","PRPS1")] #remove XIST and genes that do not converge.

LCL_all_NPX <- fit_NLS_model(data = data.lcl, meta = meta.lcl, genes = lcl_xgenes_fix, )
LCL_all_NPX_conv <- 	LCL_all_NPX[LCL_all_NPX$converged == 1,]
LCL_all_NPX_non_conv <- LCL_all_NPX[LCL_all_NPX$converged == 0,]
    interesting <- LCL_all_NPX_conv[(LCL_all_NPX_conv$a > 0.5 & LCL_all_NPX_conv$a < 1.5) & (LCL_all_NPX_conv$b > 0.25 | LCL_all_NPX_conv$b < -0.25),]
  
  # pdf(file="lcl_all_NPX_model_scatter.pdf", width=2, height=2) #un-comment for PDF
  ggplot() +
    geom_point(data=LCL_all_NPX_conv, mapping = aes(x=a, y=b), col="#00000040", stroke=0) +
    geom_text_repel(data=LCL_all_NPX_conv[rownames(interesting),], mapping = aes(x=a, y=b, label=rownames(interesting)), col="#00000040", size=2, min.segment.length = 0, box.padding = 0, force = 30) +
    geom_vline(xintercept = 1, lty=2, color="red") +
    theme_classic(base_size = 8) +
    theme(
      plot.title = ggtext::element_markdown(hjust = 0.5),
      axis.text = element_text(color = "black"), 
      axis.ticks = element_line(color = "black", size = 0.25), 
      axis.line = element_line(size = 0.25)) + xlim(-1.5,8) + ylim(-0.6,1.1) 
  
  ggplot() +
    geom_point(data=LCL_all_NPX_conv, mapping = aes(x=a, y=b), col="#00000040", stroke=0) +
    geom_text_repel(data=LCL_all_NPX_conv[rownames(interesting),], mapping = aes(x=a, y=b, label=rownames(interesting)), col="#00000040", size=2, min.segment.length = 0, box.padding = 0, force = 50) +
    geom_vline(xintercept = 1, lty=2, color="red") +
    theme_classic(base_size = 8) +
    theme(
      plot.title = ggtext::element_markdown(hjust = 0.5),
      axis.text = element_text(color = "black"), 
      axis.ticks = element_line(color = "black", size = 0.25), 
      axis.line = element_line(size = 0.25)) + xlim(0.5,1.5) + ylim(0.25,1.25)
  # dev.off()
```

## LCL "Esc" NPX
```{r}
esc_genes_balaton <- balaton_XCI_anno[balaton_XCI_anno$Balaton.consensus.calls %in% c("E","Mostly E"),"Gene"]
lcl_esc_genes <- intersect(lcl_xgenes_fix, esc_genes_balaton) #30 genes

LCL_esc_NPX <- fit_NLS_model(data = data.lcl, meta = meta.lcl, genes = lcl_esc_genes)
LCL_esc_NPX_conv <- 	LCL_esc_NPX[LCL_esc_NPX$converged == 1,]
LCL_esc_NPX_non_conv <- LCL_esc_NPX[LCL_esc_NPX$converged == 0,]
    interesting <- LCL_esc_NPX_conv[(LCL_esc_NPX_conv$a > 0.5 & LCL_esc_NPX_conv$a < 1.5) & (LCL_esc_NPX_conv$b > 0.25 | LCL_esc_NPX_conv$b < -0.25),]

  # pdf(file="lcl_esc_NPX_model_scatter.pdf", width=2, height=2) #un-comment for PDF
  ggplot() +
    geom_point(data=LCL_esc_NPX_conv, mapping = aes(x=a, y=b), col="#00000040", stroke=0) +
    # geom_text_repel(data=LCL_esc_NPX_conv[rownames(interesting),], mapping = aes(x=a, y=b, label=rownames(interesting)), col="#00000040", size=2, min.segment.length = 0, box.padding = 0, force = 30) +
    geom_vline(xintercept = 1, lty=2, color="red") +
    theme_classic(base_size = 8) +
    theme(
      plot.title = ggtext::element_markdown(hjust = 0.5),
      axis.text = element_text(color = "black"), 
      axis.ticks = element_line(color = "black", size = 0.25), 
      axis.line = element_line(size = 0.25)) + xlim(-1.5,8) + ylim(-0.6,1.1)
  
  ggplot() +
    geom_point(data=LCL_esc_NPX_conv, mapping = aes(x=a, y=b), col="#00000040", stroke=0) +
    geom_text_repel(data=LCL_esc_NPX_conv[rownames(interesting),], mapping = aes(x=a, y=b, label=rownames(interesting)), col="#00000040", size=2, min.segment.length = 0, box.padding = 0, force = 50) +
    geom_vline(xintercept = 1, lty=2, color="red") +
    theme_classic(base_size = 8) +
    theme(
      plot.title = ggtext::element_markdown(hjust = 0.5),
      axis.text = element_text(color = "black"), 
      axis.ticks = element_line(color = "black", size = 0.25), 
      axis.line = element_line(size = 0.25)) + xlim(0.5,1.5) + ylim(0.25,1.25)
  # dev.off()
  

```


## LCL "Silenced" NPX
```{r}
sil_genes_balaton <- balaton_XCI_anno[balaton_XCI_anno$Balaton.consensus.calls %in% c("S"),"Gene"]
lcl_sil_genes <- intersect(lcl_xgenes_fix, sil_genes_balaton) #255 genes

LCL_sil_NPX <- fit_NLS_model(data = data.lcl, meta = meta.lcl, genes = lcl_sil_genes)
LCL_sil_NPX_conv <- 	LCL_sil_NPX[LCL_sil_NPX$converged == 1,]
LCL_sil_NPX_non_conv <- LCL_sil_NPX[LCL_sil_NPX$converged == 0,]
    interesting <- LCL_sil_NPX_conv[(LCL_sil_NPX_conv$a > 0.5 & LCL_sil_NPX_conv$a < 1.5) & (LCL_sil_NPX_conv$b > 0.25 | LCL_sil_NPX_conv$b < -0.25),]

  
  # pdf(file="lcl_sil_NPX_model_scatter.pdf", width=2, height=2) #un-comment for PDF
  ggplot() +
    geom_point(data=LCL_sil_NPX_conv, mapping = aes(x=a, y=b), col="#00000040", stroke=0) +
    # geom_text_repel(data=LCL_sil_NPX_conv[rownames(interesting),], mapping = aes(x=a, y=b, label=rownames(interesting)), col="#00000040", size=2, min.segment.length = 0, box.padding = 0, force = 30) +
    geom_vline(xintercept = 1, lty=2, color="red") +
    theme_classic(base_size = 8) +
    theme(
      plot.title = ggtext::element_markdown(hjust = 0.5),
      axis.text = element_text(color = "black"), 
      axis.ticks = element_line(color = "black", size = 0.25), 
      axis.line = element_line(size = 0.25)) + xlim(-1.5,8) + ylim(-0.6,1.1)
  
  ggplot() +
    geom_point(data=LCL_sil_NPX_conv, mapping = aes(x=a, y=b), col="#00000040", stroke=0) +
    geom_text_repel(data=LCL_sil_NPX_conv[rownames(interesting),], mapping = aes(x=a, y=b, label=rownames(interesting)), col="#00000040", size=2, min.segment.length = 0, box.padding = 0, force = 50) +
    geom_vline(xintercept = 1, lty=2, color="red") +
    theme_classic(base_size = 8) +
    theme(
      plot.title = ggtext::element_markdown(hjust = 0.5),
      axis.text = element_text(color = "black"), 
      axis.ticks = element_line(color = "black", size = 0.25), 
      axis.line = element_line(size = 0.25)) + xlim(0.5,1.5) + ylim(0.25,1.25)
  # dev.off()
  

```



## fib all NPX
```{r}
#fib: all NPX genes
fib_xgenes <- rownames(data.fib)[!rownames(data.fib) %in% c(PAR1_genes, PAR2_genes)]
fib_xgenes_fix <- fib_xgenes[! fib_xgenes %in% c("XIST","MAGED1","NDUFA1","ZNF182")]

fib_all_NPX <- fit_NLS_model(data = data.fib, meta = meta.fib, genes = fib_xgenes_fix)
fib_all_NPX_conv <- 	fib_all_NPX[fib_all_NPX$converged == 1,]
fib_all_NPX_non_conv <- fib_all_NPX[fib_all_NPX$converged == 0,]
    interesting <- fib_all_NPX_conv[(fib_all_NPX_conv$b > 0.25 | fib_all_NPX_conv$b < -0.25),]

  
  # pdf(file="fib_all_NPX_model_scatter.pdf", width=4, height=4)
  ggplot() +
    geom_point(data=fib_all_NPX_conv, mapping = aes(x=a, y=b), col="#00000040", stroke=0) +
    geom_text_repel(data=fib_all_NPX_conv[rownames(interesting),], mapping = aes(x=a, y=b, label=rownames(interesting)), col="#00000040", size=2, min.segment.length = 0, box.padding = 0, force = 30) +
    geom_vline(xintercept = 1, lty=2, color="red") +
    theme_classic(base_size = 8) +
    theme(
      plot.title = ggtext::element_markdown(hjust = 0.5),
      axis.text = element_text(color = "black"), 
      axis.ticks = element_line(color = "black", size = 0.25), 
      axis.line = element_line(size = 0.25)) + xlim(-1.5,8)  + ylim(-0.6,1.1)
  
  ggplot() +
    geom_point(data=fib_all_NPX_conv, mapping = aes(x=a, y=b), col="#00000040", stroke=0) +
    geom_text_repel(data=fib_all_NPX_conv[rownames(interesting),], mapping = aes(x=a, y=b, label=rownames(interesting)), col="#00000040", size=2, min.segment.length = 0, box.padding = 0, force = 50) +
    geom_vline(xintercept = 1, lty=2, color="red") +
    theme_classic(base_size = 8) +
    theme(
      plot.title = ggtext::element_markdown(hjust = 0.5),
      axis.text = element_text(color = "black"), 
      axis.ticks = element_line(color = "black", size = 0.25), 
      axis.line = element_line(size = 0.25)) + xlim(0,2) + ylim(0.25,1.25)
  # dev.off()
  

```

## fib "Esc" NPX
```{r}
esc_genes_balaton <- balaton_XCI_anno[balaton_XCI_anno$Balaton.consensus.calls %in% c("E","Mostly E"),"Gene"]
fib_esc_genes <- intersect(fib_xgenes_fix, esc_genes_balaton) #30 genes

fib_esc_NPX <- fit_NLS_model(data = data.fib, meta = meta.fib, genes = fib_esc_genes)
fib_esc_NPX_conv <- 	fib_esc_NPX[fib_esc_NPX$converged == 1,]
fib_esc_NPX_non_conv <- fib_esc_NPX[fib_esc_NPX$converged == 0,]
    interesting <- fib_esc_NPX_conv[(fib_esc_NPX_conv$a > 0.5 & fib_esc_NPX_conv$a < 1.5) & (fib_esc_NPX_conv$b > 0.25 | fib_esc_NPX_conv$b < -0.25),]

  
# pdf(file="fib_esc_NPX_model_scatter.pdf", width=2, height=2)
  ggplot() +
    geom_point(data=fib_esc_NPX_conv, mapping = aes(x=a, y=b), col="#00000040", stroke=0) +
    # geom_text_repel(data=fib_esc_NPX_conv[rownames(interesting),], mapping = aes(x=a, y=b, label=rownames(interesting)), col="#00000040", size=2, min.segment.length = 0, box.padding = 0, force = 30) +
    geom_vline(xintercept = 1, lty=2, color="red") +
    theme_classic(base_size = 8) +
    theme(
      plot.title = ggtext::element_markdown(hjust = 0.5),
      axis.text = element_text(color = "black"), 
      axis.ticks = element_line(color = "black", size = 0.25), 
      axis.line = element_line(size = 0.25)) + xlim(-1.5,8) + ylim(-0.6,1.1)
  
  ggplot() +
    geom_point(data=fib_esc_NPX_conv, mapping = aes(x=a, y=b), col="#00000040", stroke=0) +
    geom_text_repel(data=fib_esc_NPX_conv[rownames(interesting),], mapping = aes(x=a, y=b, label=rownames(interesting)), col="#00000040", size=2, min.segment.length = 0, box.padding = 0, force = 50) +
    geom_vline(xintercept = 1, lty=2, color="red") +
    theme_classic(base_size = 8) +
    theme(
      plot.title = ggtext::element_markdown(hjust = 0.5),
      axis.text = element_text(color = "black"), 
      axis.ticks = element_line(color = "black", size = 0.25), 
      axis.line = element_line(size = 0.25)) + xlim(0.5,1.5) + ylim(0.25,1.25)
  # dev.off()
  

```


## fib "Silenced" NPX
```{r}
sil_genes_balaton <- balaton_XCI_anno[balaton_XCI_anno$Balaton.consensus.calls %in% c("S"),"Gene"]
fib_sil_genes <- intersect(fib_xgenes_fix, sil_genes_balaton) #255 genes

fib_sil_NPX <- fit_NLS_model(data = data.fib, meta = meta.fib, genes = fib_sil_genes)
fib_sil_NPX_conv <- 	fib_sil_NPX[fib_sil_NPX$converged == 1,]
fib_sil_NPX_non_conv <- fib_sil_NPX[fib_sil_NPX$converged == 0,]
    interesting <- fib_sil_NPX_conv[(fib_sil_NPX_conv$a > 0.5 & fib_sil_NPX_conv$a < 1.5) & (fib_sil_NPX_conv$b > 0.25 | fib_sil_NPX_conv$b < -0.25),]

 
  # pdf(file="fib_sil_NPX_model_scatter.pdf", width=2, height=2)
  ggplot() +
    geom_point(data=fib_sil_NPX_conv, mapping = aes(x=a, y=b), col="#00000040", stroke=0) +
    # geom_text_repel(data=fib_sil_NPX_conv[rownames(interesting),], mapping = aes(x=a, y=b, label=rownames(interesting)), col="#00000040", size=2, min.segment.length = 0, box.padding = 0, force = 30) +
    geom_vline(xintercept = 1, lty=2, color="red") +
    theme_classic(base_size = 8) +
    theme(
      plot.title = ggtext::element_markdown(hjust = 0.5),
      axis.text = element_text(color = "black"), 
      axis.ticks = element_line(color = "black", size = 0.25), 
      axis.line = element_line(size = 0.25)) + xlim(-1.5,8) + ylim(-0.6,1.1)
  
  ggplot() +
    geom_point(data=fib_sil_NPX_conv, mapping = aes(x=a, y=b), col="#00000040", stroke=0) +
    geom_text_repel(data=fib_sil_NPX_conv[rownames(interesting),], mapping = aes(x=a, y=b, label=rownames(interesting)), col="#00000040", size=2, min.segment.length = 0, box.padding = 0, force = 50) +
    geom_vline(xintercept = 1, lty=2, color="red") +
    theme_classic(base_size = 8) +
    theme(
      plot.title = ggtext::element_markdown(hjust = 0.5),
      axis.text = element_text(color = "black"), 
      axis.ticks = element_line(color = "black", size = 0.25), 
      axis.line = element_line(size = 0.25)) + xlim(0.5,1.5) + ylim(0.25,1.25)
  # dev.off()
  

```
#PAR genes 
```{r}
#model as a function of total sex chr number for this purpose
fit_NLS_model_PAR_total <- function(data, meta, genes, myMax = 100, start_a = 1, start_b = 0.5){
  
  # meta <- meta.lcl
  # data <- data.lcl
  # genes <- lcl_PARgenes
  # myMax <- 100
  # start_a <- 1
  # start_b <- 0.5
# format data
  rownames(meta) <- meta$sample
  meta$chrom_count <- meta$x_count + meta$y_count
	mod <- model.matrix(~x_count + y_count + chrom_count, meta[colnames(data), ])
	mod[, 4] <- mod[, 4] - 1
	df <- t(data[genes, ])
	# normalize data to appropriate mean value
	# normalize to mean of samples with one X
	b0s <- apply(df[rownames(mod[mod[, 4]==0, ]),], 2, mean)
	df <- t(t(df) / b0s)

	# fit
	coefs <- list()
	for (g in genes) {
	   # g <- genes[1]
		df.g <- data.frame(cts=df[, g], x_count=mod[, 2], y_count=mod[, 3],
						   chrom_count=mod[, 4])
		m.g <- nlsLM(cts ~ 1 + b * chrom_count ^ a, df.g, start=list(a=start_a, b=start_b), control = nls.lm.control(maxiter = myMax,))
		coefs[[g]] <- c(m.g$m$getPars(), converged=m.g$convInfo$isConv, numConv = m.g$convInfo$finIter)
	}
	coefs <- as.data.frame(t(data.frame(coefs)))
	return(coefs)
}


lcl_PARgenes <- rownames(data.lcl)[rownames(data.lcl) %in% c(PAR1_genes, PAR2_genes)]

LCL_PAR <- fit_NLS_model_PAR_total(data = data.lcl, meta = meta.lcl, genes = lcl_PARgenes)
LCL_PAR_conv <- 	LCL_PAR[LCL_PAR$converged == 1,]
LCL_PAR_non_conv <- LCL_PAR[LCL_PAR$converged == 0,]
  
  myGreen <- "#1B9E7795"
  
  # pdf(file="LCL_PAR_model_scatter.pdf", width=2, height=2)
  ggplot() +
    geom_point(data=LCL_PAR_conv[rownames(LCL_PAR_conv) %in% PAR1_genes,], mapping = aes(x=a, y=b), col=myGreen, stroke=0) +
    geom_point(data=LCL_PAR_conv[rownames(LCL_PAR_conv) %in% PAR2_genes,], mapping = aes(x=a, y=b), col="#1B9E7740", stroke=0) +
    geom_vline(xintercept = 1, lty=2, color="red") +
    theme_classic(base_size = 8) +
    theme(
      plot.title = ggtext::element_markdown(hjust = 0.5),
      axis.text = element_text(color = "black"), 
      axis.ticks = element_line(color = "black", size = 0.25), 
      axis.line = element_line(size = 0.25)) + ylim(-0.6,1.2) + xlim(0,2)
  # dev.off()
  
  fib_PARgenes <- rownames(data.fib)[rownames(data.fib) %in% c(PAR1_genes, PAR2_genes)]

  
  fib_PAR <- fit_NLS_model_PAR_total(data = data.fib, meta = meta.fib, genes = fib_PARgenes)
fib_PAR_conv <- 	fib_PAR[fib_PAR$converged == 1,]
fib_PAR_non_conv <- fib_PAR[fib_PAR$converged == 0,]

  
   # pdf(file="fib_PAR_model_scatter.pdf", width=2, height=2)
  ggplot() +
    geom_point(data=fib_PAR_conv[rownames(fib_PAR_conv) %in% PAR1_genes,], mapping = aes(x=a, y=b), col=myGreen, stroke=0) +
    geom_point(data=fib_PAR_conv[rownames(fib_PAR_conv) %in% PAR2_genes,], mapping = aes(x=a, y=b), col="#1B9E7740", stroke=0) +
    geom_vline(xintercept = 1, lty=2, color="red") +
    theme_classic(base_size = 8) +
    theme(
      plot.title = ggtext::element_markdown(hjust = 0.5),
      axis.text = element_text(color = "black"), 
      axis.ticks = element_line(color = "black", size = 0.25), 
      axis.line = element_line(size = 0.25)) + ylim(-0.6,1.2) + xlim(0,2)
  # dev.off()
```

#NPY genes 
```{r}
#model as a function of total sex chr number for this purpose
fit_NLS_model_NPY <- function(data, meta, genes, myMax = 100, start_a = 1, start_b = 0.5){
  # meta <- meta.lcl.y
  # data <- data.lcl.y
  # genes <- lcl_NPYgenes
  # myMax <- 100
  # start_a <- 1
  # start_b <- 0.5
# format data
  rownames(meta) <- meta$sample
	mod <- model.matrix(~x_count + y_count, meta[colnames(data), ])
	mod[, 3] <- mod[, 3] - 1
	df <- t(data[genes, ])
	# normalize data to appropriate mean value
	# normalize to mean of samples with one Y
	b0s <- apply(df[rownames(mod[mod[, 3]==0, ]),], 2, mean)
	df <- t(t(df) / b0s)

	# fit
	coefs <- list()
	for (g in genes) {
	   #g <- genes[1]
		df.g <- data.frame(cts=df[, g], x_count=mod[, 2], y_count=mod[, 3])
		m.g <- nlsLM(cts ~ 1 + b * y_count ^ a, df.g, start=list(a=start_a, b=start_b), control = nls.lm.control(maxiter = myMax,))
		coefs[[g]] <- c(m.g$m$getPars(), converged=m.g$convInfo$isConv, numConv = m.g$convInfo$finIter)
	}
	coefs <- as.data.frame(t(data.frame(coefs)))
	return(coefs)
}

lcl_NPYgenes <- rownames(data.lcl.y)

LCL_NPY <- fit_NLS_model_NPY(data = data.lcl.y, meta = meta.lcl.y, genes = lcl_NPYgenes)
LCL_NPY_conv <- 	LCL_NPY[LCL_NPY$converged == 1,]
LCL_NPY_non_conv <- LCL_NPY[LCL_NPY$converged == 0,]

  # pdf(file="LCL_NPY_model_scatter.pdf", width=2, height=2)
  ggplot() +
    geom_point(data=LCL_NPY_conv, mapping = aes(x=a, y=b), col="#00000040", stroke=0) +
    geom_vline(xintercept = 1, lty=2, color="red") +
    theme_classic(base_size = 8) +
    theme(
      plot.title = ggtext::element_markdown(hjust = 0.5),
      axis.text = element_text(color = "black"), 
      axis.ticks = element_line(color = "black", size = 0.25), 
      axis.line = element_line(size = 0.25)) +xlim(0,2) + ylim(-0.5,1.4)
  # dev.off()
  
 fib_NPYgenes <- rownames(data.fib.y)

fib_NPY <- fit_NLS_model_NPY(data = data.fib.y, meta = meta.fib.y, genes = fib_NPYgenes)
fib_NPY_conv <- 	fib_NPY[fib_NPY$converged == 1,]
fib_NPY_non_conv <- fib_NPY[fib_NPY$converged == 0,]


  # pdf(file="fib_NPY_model_scatter.pdf", width=2, height=2)
  ggplot() +
    geom_point(data=fib_NPY_conv, mapping = aes(x=a, y=b), col="#00000040", stroke=0) +
    geom_vline(xintercept = 1, lty=2, color="red") +
    theme_classic(base_size = 8) +
    theme(
      plot.title = ggtext::element_markdown(hjust = 0.5),
      axis.text = element_text(color = "black"), 
      axis.ticks = element_line(color = "black", size = 0.25), 
      axis.line = element_line(size = 0.25)) +xlim(0,2) + ylim(-0.5,1.4)
  # dev.off()
```

```{r}
sessionInfo()
```

